"""updated class ledger with datetime

Revision ID: 489ef84a4773
Revises: dfdc9c618865
Create Date: 2026-09-30 01:05:58.811764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489ef84a4773'
down_revision: Union[str, Sequence[str], None] = 'dfdc9c618865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journalentrylines', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journalentrylines', 'created_at')
    # ### end Alembic commands ###
