"""creating the user and profile

Revision ID: db91aac58668
Revises: 88b57a7a3574
Create Date: 2026-09-20 00:04:05.124375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db91aac58668'
down_revision: Union[str, Sequence[str], None] = '88b57a7a3574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('phonenumber', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.alter_column('ledgeraccounts', 'ledgeraccountname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'ledgeraccounts', ['ledgeraccountname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ledgeraccounts', type_='unique')
    op.alter_column('ledgeraccounts', 'ledgeraccountname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('profiles')
    # ### end Alembic commands ###
