"""adding transactions mpesa_receipt and conversation_id column

Revision ID: dfa17b0fcf75
Revises: f9d2e827e7dc
Create Date: 2026-09-05 22:48:29.226212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa17b0fcf75'
down_revision: Union[str, Sequence[str], None] = 'f9d2e827e7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('mpesa_reciept', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('checkout_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'checkout_id')
    op.drop_column('transactions', 'mpesa_reciept')
    # ### end Alembic commands ###
