"""update

Revision ID: f9d2e827e7dc
Revises: ab02b03a2f4a
Create Date: 2026-08-28 00:43:24.405183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d2e827e7dc'
down_revision: Union[str, Sequence[str], None] = 'ab02b03a2f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journalentrylines', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.drop_column('journalentrylines', 'account_id')
    op.add_column('ledgeraccountlines', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('ledgeraccountlines_membership_key'), 'ledgeraccountlines', type_='unique')
    op.drop_column('ledgeraccountlines', 'membership')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledgeraccountlines', sa.Column('membership', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('ledgeraccountlines_membership_key'), 'ledgeraccountlines', ['membership'], postgresql_nulls_not_distinct=False)
    op.drop_column('ledgeraccountlines', 'wallet_id')
    op.add_column('journalentrylines', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('journalentrylines', 'wallet_id')
    # ### end Alembic commands ###
